#!/usr/bin/env bash

set -euo pipefail

REPLACEMENT=$(cat zprintf | python minifier.py | ./quote-js)

export REPLACEMENT

perl -0777 -i -pe 's/(::START::[^\n]*\n\s*).*(\n[^\n]*::END::)/$1.$ENV{'REPLACEMENT'}.$2/se' zprint-mode.el
