#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Updates zprint-mode.el from minified
# bash file. Needs to be re-run when you
# change zprint-filter

REPLACEMENT=$(cat scripts/zprint-filter | python scripts/minifier.py | scripts/quote-js)

export REPLACEMENT

perl -0777 -i -pe 's/(::START::[^\n]*\n\s*).*(\n[^\n]*::END::)/$1.$ENV{'REPLACEMENT'}.$2/se' zprint-mode.el
