#!/usr/bin/env bash
set -euo pipefail && cd "$(dirname "${BASH_SOURCE[0]}")/.."

our_temp_dir=$(mktemp -d 2>/dev/null || mktemp -d -t "our_temp_dir")
function cleanup_temp_dir() { rm -rf "$our_temp_dir" ; } && trap "cleanup_temp_dir" EXIT

set -x

ret=0 && scripts/wrap-zprint tests/samples/good.clj "$our_temp_dir/out.clj" || ret=$?

if [[ "$ret" != 0 ]]; then
    echo Assertion failed
    exit 1
fi

ret=0 && scripts/wrap-zprint tests/samples/bad.clj "$our_temp_dir/out.clj" || ret=$?

if [[ "$ret" == 0 ]]; then
    echo Assertion failed
    exit 1
fi

echo All OK
